#ifndef CONSTANTS_H
#define CONSTANTS_H


typedef enum ErrorCode {
    ERR_NONE = 0x00,
    ERR_NULL_PTR = 0x01,
    ERR_MALLOC_FAILED = 0x02,
    ERR_INVALID_INDEX = 0x03,
    ERR_LIST_EMPTY = 0x04,
    ERR_INVALID_HEAD_PTR = 0x05,
    ERR_INVALID_ARGS = 0x06,
    ERR_INVALID_TAIL_PTR = 0x07,
    ERR_REALLOC_FAILED = 0x08,
    ERR_DATATYPE_MISMATCH = 0x09,
    ERR_DIMENSION_SIZE_MISMATCH = 0xA,
    ERR_DIMENSION_COUNT_MISMATCH = 0xB,
    ERR_UNSUPPORTED_DATATYPE = 0xC,
    ERR_UNKNOWN = 0xFF
} ErrorCode;

typedef enum Boolean {
    FALSE,
    TRUE
} Boolean;

#endif // CONSTANTS_H
